### PR TITLE
Fixed energy issues

### LINKED ISSUE #41: Inscriber doesn't operate
It does nothing. And yes, im aware of tile entity desync

### LINKED ISSUE #45: Batteries eat power
https://i.dbot.serealia.ca/2018/02/2018-02-15_06-31-33.mp4

Instead of recharge, ~~batteries "eat" Forge Energy~~ batteries visually eat forge energy

### PR DESCRIPTION
**Pull request by DBotThePony**
All batteries and weapons after change **will** lose their current energy.
All machines **have** to be replaced after update:
lol

This PR changes seriable capabilities into regular NBT tags.
This workarounds https://github.com/MinecraftForge/MinecraftForge/issues/3483
Also this re-enables old code to send energy update packet to clients because it seems to be stable and working.

This fixes https://github.com/MatterOverdrive/MatterOverdrive/issues/45
This also fixes https://github.com/MatterOverdrive/MatterOverdrive/issues/41

*first pull request in minecraft modding ever*

### CODE REVIEW

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java [hunk 1]
```diff
@@ -25,28 +28,117 @@ public void setFull() {
...
+        return energyExtracted;
+    }
+
     public NBTTagCompound serializeNBT() {
         NBTTagCompound tag = new NBTTagCompound();
-        tag.setInteger("energy", energy);
-        tag.setInteger("capacity", capacity);
-        tag.setInteger("maxReceive", maxReceive);
-        tag.setInteger("maxExtract", maxExtract);
+        tag.setInteger("mo_energystored", energy);
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: Is there a reason why all the nbt tags have to change? this breaks backward compat for no *real* reason

File: src/main/java/matteroverdrive/tile/MOTileEntityMachineEnergy.java [hunk 2]
```diff
@@ -107,7 +110,7 @@ public int getFreeEnergySpace() {
     }
 
     public void UpdateClientPower() {
-        //MatterOverdrive.packetPipeline.sendToAllAround(new PacketPowerUpdate(this), new NetworkRegistry.TargetPoint(world.provider.getDimension(), getPos().getX(), getPos().getY(), getPos().getZ(), ENERGY_CLIENT_SYNC_RANGE));
+        MatterOverdrive.packetPipeline.sendToAllAround(new PacketPowerUpdate(this), new NetworkRegistry.TargetPoint(world.provider.getDimension(), getPos().getX(), getPos().getY(), getPos().getZ(), ENERGY_CLIENT_SYNC_RANGE));
```
Comment (adrwa) [inline src/main/java/matteroverdrive/tile/MOTileEntityMachineEnergy.java]: This was already done in a previous commit

**Review by adrwa — CHANGES_REQUESTED** [review]

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java (hunk 1 above)
Comment (DBotThePony) [reply src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: It doesn't break. There is no backward compability, because before all tags were stored in Item/ForgeCaps/Parent, now they are in Item/nbt

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java [hunk 3]
```diff
@@ -25,13 +28,103 @@ public void setFull() {
...
+    @Override
+    public int extractEnergy(int amount, boolean simulate) {
+        if (!canExtract())
+            return 0;
+
+        int energyExtracted = Math.min(getEnergyStored(), Math.min(getMaxExtract(), amount));
+
+        if (!simulate) {
+            if (stack != null && energyExtracted != 0) {
+                stack.getTagCompound().setInteger("mo_energystored", getEnergyStored() - energyExtracted);
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: Change this to the same value as below

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java [hunk 4]
```diff
@@ -25,13 +28,103 @@ public void setFull() {
...
+        if (stack != null) {
+            return stack.getTagCompound().getInteger("mo_capacity");
+        }
+
+        return capacity;
+    }
+
+    public int getMaxExtract() {
+        if (stack != null) {
+            return stack.getTagCompound().getInteger("mo_maxextract");
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: Change this to the same value as below

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java [hunk 5]
```diff
@@ -25,13 +28,103 @@ public void setFull() {
...
+        }
+
+        return maxExtract;
+    }
+
+    public int getMaxReceive() {
+        if (stack != null) {
+            return stack.getTagCompound().getInteger("mo_maxreceive");
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: Change this to the same value as below

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java [hunk 6]
```diff
@@ -25,13 +28,103 @@ public void setFull() {
...
+    @Override
+    public int receiveEnergy(int amount, boolean simulate) {
+        if (!canReceive())
+            return 0;
+
+        int energyReceived = Math.min(getMaxEnergyStored() - getEnergyStored(), Math.min(getMaxReceive(), amount));
+
+        if (!simulate) {
+            if (stack != null && energyReceived != 0) {
+                stack.getTagCompound().setInteger("mo_energystored", getEnergyStored() + energyReceived);
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: Change this to the same value as below

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java [hunk 7]
```diff
@@ -25,13 +28,103 @@ public void setFull() {
...
+            return stack.getTagCompound().getInteger("mo_energystored");
+        }
+
+        return energy;
+    }
+
+    @Override
+    public int getMaxEnergyStored() {
+        if (stack != null) {
+            return stack.getTagCompound().getInteger("mo_capacity");
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: Change this to the same value as below

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java [hunk 8]
```diff
@@ -25,13 +28,103 @@ public void setFull() {
...
+
+        deserializeNBT(stack.getTagCompound());
+        this.stack = stack;
+        return this;
+    }
+
+    @Override
+    public int getEnergyStored() {
+        if (stack != null) {
+            return stack.getTagCompound().getInteger("mo_energystored");
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: Change this to the same value as below

**Review by adrwa — CHANGES_REQUESTED** [review]

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java [hunk 9]
```diff
@@ -1,10 +1,14 @@
 package matteroverdrive.items.includes;
 
+import net.minecraft.item.ItemStack;
 import net.minecraft.nbt.NBTTagCompound;
+import net.minecraftforge.common.util.Constants;
 import net.minecraftforge.common.util.INBTSerializable;
 import net.minecraftforge.energy.EnergyStorage;
 
 public class EnergyContainer extends EnergyStorage implements INBTSerializable<NBTTagCompound> {
+    ItemStack stack;
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: Please make this private final with a getter

File: src/main/java/matteroverdrive/items/includes/EnergyContainer.java [hunk 10]
```diff
@@ -25,13 +29,123 @@ public void setFull() {
...
+            tag.setTag("energy",  serializeNBT());
+        } else {
+            deserializeNBT(stack.getTagCompound().getCompoundTag("energy"));
+        }
+
+        this.stack = stack;
+        return this;
+    }
+
+    private NBTTagCompound stackTag() {
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/EnergyContainer.java]: please rename this method to getStackEnergyTag

File: src/main/java/matteroverdrive/items/includes/MOItemEnergyContainer.java [hunk 11]
```diff
@@ -45,9 +47,7 @@ public MOItemEnergyContainer(String name) {
     }
 
     public static IEnergyStorage getStorage(ItemStack stack) {
-        if (stack.hasCapability(CapabilityEnergy.ENERGY, null))
-            return stack.getCapability(CapabilityEnergy.ENERGY, null);
-        return EmptyEnergyStorage.INSTANCE;
```
Comment (adrwa) [inline src/main/java/matteroverdrive/items/includes/MOItemEnergyContainer.java]: This shouldn't be removed, its a very important piece of code

**Review by adrwa — CHANGES_REQUESTED** [review]

**Review by adrwa — APPROVED** [review]
